### PR TITLE
Why is the dependency on vscode-kubernetes added during release? #3091

### PR DESCRIPTION
**Pull request by vrubezhny**
Fixes: #3091

### CODE REVIEW

**Review by datho7561 — COMMENTED** [review]
Looks good so far, integration tests are passing for me. You will need to remove the part in the Jenkinsfile that adds the Kubernetes extension to the package.json

**Comment by vrubezhny** [comment]
> Looks good so far, integration tests are passing for me. 
Yes, but have you tried running tests from vscode run "Extension Debug Tests" on Debug view?

> You will need to remove the part in the Jenkinsfile that adds the Kubernetes extension to the package.json
Sure I'll remove this part

**Comment by datho7561** [comment]
The tests suites seem debuggable to me, but I needed to add the following:

```diff
diff --git a/.vscode/launch.json b/.vscode/launch.json
index 7f70119d..227fe9be 100644
--- a/.vscode/launch.json
+++ b/.vscode/launch.json
@@ -74,7 +74,8 @@
             "sourceMaps": true,
             "preLaunchTask": "instrument",
             "env": {
-                "VSCODE_REDHAT_TELEMETRY_DEBUG":"true"
+                "VSCODE_REDHAT_TELEMETRY_DEBUG": "true",
+                "IS_OPENSHIFT": "true",
             }
         },
         {
```

for the integration test suite, since I'm using an OpenShift cluster

**Comment by vrubezhny** [comment]
> The tests suites seem debuggable to me, but I needed to add the following:
> 
> ```diff
> diff --git a/.vscode/launch.json b/.vscode/launch.json
> index 7f70119d..227fe9be 100644
> --- a/.vscode/launch.json
> +++ b/.vscode/launch.json
> @@ -74,7 +74,8 @@
>              "sourceMaps": true,
>              "preLaunchTask": "instrument",
>              "env": {
> -                "VSCODE_REDHAT_TELEMETRY_DEBUG":"true"
> +                "VSCODE_REDHAT_TELEMETRY_DEBUG": "true",
> +                "IS_OPENSHIFT": "true",
>              }
>          },
>          {
> ```
> 
> for the integration test suite, since I'm using an OpenShift cluster

Added `"IS_OPENSHIFT": "true"` to `launch.json`

**Pull request merged**
