### PR TITLE
Updated debug gifs with the latest workflow

### PR DESCRIPTION
**Pull request by msivasubramaniaan**
Updated debug gifs with the latest workflow.

Ref: https://github.com/redhat-developer/vscode-openshift-tools/issues/2459

### CODE REVIEW

**Review by dgolovin — COMMENTED** [review]
Why are you replacing remote debugger for local one?

**Comment by msivasubramaniaan** [comment]
> Why are you replacing remote debugger for local one?

changed to remote debugger

**Review by dgolovin — CHANGES_REQUESTED** [review]
1. Lets use the same size for animated gifs that captures full vscode window. I would suggest to use HD resolution width 1280x720 to keep file size under control.
2. NodeJS debug content seems to be fine except the image size is FHD and there is screen recording tool window visible in the end and should be removed
3. Java debug missing the step to show Java extension installation, because it can be not installed by default.
4. The waiting time for debug session start should be reduced to reduce gif size

**Comment by msivasubramaniaan** [comment]
> 1. Lets use the same size for animated gifs that captures full vscode window. I would suggest to use HD resolution width 1280x720 to keep file size under control.
> 2. NodeJS debug content seems to be fine except the image size is FHD and there is screen recording tool window visible in the end and should be removed
> 3. Java debug missing the step to show Java extension installation, because it can be not installed by default.
> 4. The waiting time for debug session start should be reduced to reduce gif size

Addressed all the given points and changed the gif accordingly. Kindly have a look

**Review by dgolovin — APPROVED** [review]

**Pull request merged**
