### PR TITLE
CodeLens to apply a k8s YAML file

### LINKED ISSUE #2873: Add CodeLens for create/delete resource from YAML
It would be nice to have CodeLens to create or delete resources on the cluster from a YAML file.

Currently we have the "OpenShift: Create" command that creates resources from a YAML file, but this feature would be more visible if it appears in the document. It would be nice to also integrate with vscode-yaml in order to only show this popup when the file is a Kubernetes file (i.e. it is linked to a Kubernetes schema)

### PR DESCRIPTION
**Pull request by datho7561**
To try out this PR, try cloning https://github.com/quarkusio/quarkus-super-heroes and open one of the YAML files under `./deploy/k8s`. Once the extension is activated, there should be a new CodeLens at the top of the file.

This CodeLens will not appear in `devfile.yaml`.

Closes #2873

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
oops I should also provide the option to delete

**Comment by mohitsuman** [comment]
@datho7561 what is the usecase for this PR ?

Is it to directly apply the deployment YAML file to the cluster using kubectl ? Can you please summarise how this will impact/improve the workflow.

**Comment by datho7561** [comment]
It makes the existing feature to apply the YAML more visible

**Comment by datho7561** [comment]
A bug I expect this to have currently is that it won't handle detecting multi resource Kubernetes files, and I expect it will crash with an error log if the YAML file contains misformed YAML.

**Pull request merged**
