### PR TITLE
add local image to webview

### LINKED ISSUE #1754: Provide RedHat OpenShift logo in 'Add OpenShift Cluster' editor for dark and light color themes
Current presentation in dark and light theme:

image

image

### PR DESCRIPTION
**Pull request by mohitsuman**
Fix #1754

When you open `Add OpenShift Cluster` , the webview should show Red Hat OpenShift logo at the top and the cards placed below it.

Screenshot 2020-09-25 at 10 11 24 PM

### CODE REVIEW

**Comment by lstocchi** [comment]
@mohitsuman i'm quite newbie with react so not sure if this is the correct way but what i did is...
add a `window.icon = "%IMG%"` to the `index.html` -> to pass the right path of the icon (i read it needs the full path) from the `clusterViewLoader.ts` i used 
```
return `${htmlString}`
            .replace('%COMMAND%', '')
            .replace('%PLATFORM%', process.platform)
            .replace('clusterViewer.js',`${reactAppUri}`)
            .replace('<!-- meta http-equiv="Content-Security-Policy" -->', meta)
            .replace('%IMG%', panel.webview.asWebviewUri(vscode.Uri.file(path.join(reactAppRootOnDisk, '/images/logo.png'))).toString());
```
then, inside cluster.tsx 
```
declare global {
  interface Window {
      icon: any;
  }
}
const imageSrc = window.icon;
```
and finally the img-src value inside the Content-Security-Policy
```
const meta = `<meta http-equiv="Content-Security-Policy"
        content="connect-src *;
            default-src 'none';
            img-src https: vscode-resource:;
            script-src 'unsafe-eval' 'unsafe-inline' vscode-resource:;
            style-src 'self' vscode-resource: 'unsafe-inline';">`;
```

**Comment by mohitsuman** [comment]
> ```
> return `${htmlString}`
>             .replace('%COMMAND%', '')
>             .replace('%PLATFORM%', process.platform)
>             .replace('clusterViewer.js',`${reactAppUri}`)
>             .replace('', meta)
>             .replace('%IMG%', panel.webview.asWebviewUri(vscode.Uri.file(path.join(reactAppRootOnDisk, '/images/logo.png'))).toString());
> ```

What if we have multiple images to use and load. It should ideally just take the root path of the images.

**Comment by lstocchi** [comment]
> @lstocchi What if we have multiple images to use and load. It should ideally just take the root path of the images.

I agree but I really have no idea if it's possible. As i said i never used webview/react before, maybe someone else can be more helpful, sorry :/

**Comment by mohitsuman** [comment]
> > @lstocchi What if we have multiple images to use and load. It should ideally just take the root path of the images.
> 
> I agree but I really have no idea if it's possible. As i said i never used webview/react before, maybe someone else can be more helpful, sorry :/

It's something vscode webview api should streamline. But thanks for your help, really appreciate. If nothing works, we can have this temp fix.

**Comment by evidolob** [comment]
@mohitsuman In case if you need to load multiple resources(images) the easiest way will be to embed that resources as data url(base64), you can try  https://webpack.js.org/loaders/url-loader/ or https://www.npmjs.com/package/base64-inline-loader

**Comment by evidolob** [comment]
@mohitsuman With https://www.npmjs.com/package/base64-inline-loader I got load images, I can provide PR or send you a patch
Screenshot 2020-09-25 at 12 55 19

**Comment by mohitsuman** [comment]
@evidolob can you please send the patch. Does it take care the scenario when we need to provide multiple local files to the webview ?

**Comment by evidolob** [comment]
Yes, it can handle all images

**Comment by evidolob** [comment]
```patch
diff --git a/package.json b/package.json
index 23cbc13..6a10649 100644
--- a/package.json
+++ b/package.json
@@ -62,6 +62,7 @@
   },
   "dependencies": {
     "@kubernetes/client-node": "^0.11.1",
+    "base64-inline-loader": "^1.1.1",
     "binary-search": "^1.3.6",
     "byline": "^5.0.0",
     "fs-extra": "^8.1.0",
diff --git a/src/view/cluster/clusterViewLoader.ts b/src/view/cluster/clusterViewLoader.ts
index 366844a..9869a55 100644
--- a/src/view/cluster/clusterViewLoader.ts
+++ b/src/view/cluster/clusterViewLoader.ts
@@ -136,7 +136,7 @@ export default class ClusterViewLoader {
         const meta = `<meta http-equiv="Content-Security-Policy"
         content="connect-src *;
             default-src 'none';
-            img-src ${panel.webview.cspSource} https:;
+            img-src ${panel.webview.cspSource} https: 'self' data:;
             script-src 'unsafe-eval' 'unsafe-inline' vscode-resource:;
             style-src 'self' vscode-resource: 'unsafe-inline';">`;
         return `${htmlString}`
@@ -145,4 +145,4 @@ export default class ClusterViewLoader {
             .replace('clusterViewer.js',`${reactAppUri}`)
             .replace('<!-- meta http-equiv="Content-Security-Policy" -->', meta);
     }
-}
\ No newline at end of file
+}
diff --git a/src/view/cluster/webpack.config.js b/src/view/cluster/webpack.config.js
index 97b54f9..e9d53dd 100644
--- a/src/view/cluster/webpack.config.js
+++ b/src/view/cluster/webpack.config.js
@@ -40,16 +40,8 @@ module.exports = {
         ]
       },
       {
-        test: /\.(svg|png|jpg|gif)$/,
-        use: [
-          {
-            loader: 'file-loader',
-            options: {
-              name: 'images/[name].[ext]',
-              esModule: false
-            },
-          },
-        ],
+        test: /\.(jpe?g|png|ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
+        use: 'base64-inline-loader?limit=1000&name=[name].[ext]'
       }
     ]
   },
@@ -62,4 +54,4 @@ module.exports = {
        filename: 'index.html'
     })
  ]
-};
\ No newline at end of file
+};

```

**Pull request merged**
