### PR TITLE
Wrap tool location in \" to work nice with locations that has spaces

### LINKED ISSUE #338: Support space in paths
in log I have:

```
'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Aurelien Pupier\.vs-openshift\odo.exe version

'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
```

I tried command "New" from command palette and it was mentioning that it doesn't exist

### PR DESCRIPTION
**Pull request by dgolovin**
Fix #338.

### CODE REVIEW

**Comment by apupier** [comment]
it works better but there are still some ```
'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
```  in the log.
searching in which cases it happens...

full current log (in case it can give you an idea what to try):

```
C:\Users\Aurelien Pupier\.vs-openshift\odo.exe version

'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
"C:\Users\Aurelien Pupier\.vs-openshift\odo.exe" version && "C:\Users\Aurelien Pupier\.vs-openshift\odo.exe" project list
odo v0.0.16 (82968cb0)

Server: https://172.18.93.44:8443
OpenShift: v3.10.45
Kubernetes: v1.10.0+b81c8f8
ACTIVE   NAME
         circuitbreaker-booster
  *      rest-http-booster

C:\Users\Aurelien Pupier\.vs-openshift\oc.exe version

'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
"C:\Users\Aurelien Pupier\.vs-openshift\oc.exe" get project -o jsonpath="{range .items[*]}{.metadata.name}{\"\n\"}{end}"
circuitbreaker-booster
rest-http-booster

"C:\Users\Aurelien Pupier\.vs-openshift\oc.exe" get dc --namespace rest-http-booster -o jsonpath="{range .items[?(.metadata.labels.app == \"rest-http-booster\")]}{.metadata.labels.app\.kubernetes\.io/component-name}{\"\n\"}{end}"
http-booster
```

**Comment by apupier** [comment]
hum seems it is when the oc or odo version is called

```
C:\Users\Aurelien Pupier.vs-openshift\odo.exe version

'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
```

when calling "About from command palette it is working:

```
C:\Users\Aurelien Pupier\AppData\Local\Programs\Microsoft VS Code>odo version
odo v0.0.16 (82968cb0)

Server: https://172.18.93.44:8443
OpenShift: v3.10.45
Kubernetes: v1.10.0+b81c8f8
```

**Comment by apupier** [comment]
it might be due to this line https://github.com/redhat-developer/vscode-openshift-tools/blob/f00c24f80fa3dd5cb37cf88754307f0412c521b1/src/tools.ts#L166

should we fix it here? or having this place reusing the common code?

this error is causing to redownloading the oc/odo executable on each startup

**Comment by apupier** [comment]
@dgolovin provided https://github.com/dgolovin/vscode-openshift-tools/pull/1

**Comment by dgolovin** [comment]
@apupier good catch, thanks! I fixed that by calling `odo.execute()` rather than `cli.execute()`

**Comment by dgolovin** [comment]
@apupier my fix would not work, reverted and applied what you suggested.

**Pull request merged**
