### PR TITLE
fixed CRC status indications and some UI improvements

### PR DESCRIPTION
**Pull request by msivasubramaniaan**
Fixes: https://github.com/redhat-developer/vscode-openshift-tools/issues/3723

### CODE REVIEW

**Comment by mohitsuman** [comment]
@msivasubramaniaan please add the new UI screenshot.

**Comment by msivasubramaniaan** [comment]
> @msivasubramaniaan please add the new UI screenshot. A gif would be better to show the responsiveness of the UI.

FYR

https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/449eb64f-09a4-4007-ba8f-e4eeaae0131a

**Comment by mohitsuman** [comment]
How does it look for Started CRC cluster ?

**Comment by msivasubramaniaan** [comment]
> How does it look for Started CRC cluster ?

image
image

**Review by mohitsuman — APPROVED** [review]
lgtm

**Pull request merged**
