### PR TITLE
rearranged the explorer view

### PR DESCRIPTION
**Pull request by msivasubramaniaan**
image

### CODE REVIEW

**Comment by datho7561** [comment]
I don't understand how different resource types are being grouped together here. Deployments are a type of workload (see https://kubernetes.io/docs/concepts/workloads/controllers/).

**Comment by mohitsuman** [comment]
> I don't understand how different resource types are being grouped together here. Deployments are a type of workload (see https://kubernetes.io/docs/concepts/workloads/controllers/).

We can separate deployment as an individual tree as we want OpenShift devs to focus more on that. All other controllers can go inside the Workload tree, so that the view is clean.

**Comment by mohitsuman** [comment]
@datho7561 can you please review this and merge once approved ?

**Review by datho7561 — APPROVED** [review]
Works well.

**Pull request merged**
