### PR TITLE
add delete storage action

### LINKED ISSUE #136: unmount and delete actions for storage operations

### PR DESCRIPTION
**Pull request by mohitsuman**
FIx #136

### CODE REVIEW

**Comment by jrichter1** [comment]
I'm getting this from odo 0.0.13
```
Error: unknown flag: --component
Usage:
  odo storage delete [flags]

Examples:
  # Delete storage mystorage from the currently active component
  odo storage delete mystorage

  # Delete storage mystorage from component 'mongodb'
  odo storage delete mystorage --component mongodb
```

**Comment by mohitsuman** [comment]
testPR

**Comment by mohitsuman** [comment]
testPR

**Comment by mohitsuman** [comment]
testPR

**Comment by mohitsuman** [comment]
testPR

**Comment by mohitsuman** [comment]
testPR

**Comment by mohitsuman** [comment]
testPR

**Pull request merged**
