### PR TITLE
loading deployment confguration

### PR DESCRIPTION
**Pull request by msivasubramaniaan**
Fixes: https://github.com/redhat-developer/vscode-openshift-tools/issues/3928

Note: I have taken the code from https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/7e5c5f6082112314d189a4a88dc5173a8303a5e4/src/kuberesources.virtualfs.ts#L19 and added undefined check on our extension as there were no active development on vscode-kubernetes-tools. Moving forward we should plan to get rid of the vscode-kubernetes-tools dependency on our extension

### CODE REVIEW

**Comment by datho7561** [comment]
Doesn't work for me, still broken on Linux.

**Comment by msivasubramaniaan** [comment]
> Doesn't work for me, still broken on Linux.

I am not having Linux machine, I don't know how to test over it

**Comment by datho7561** [comment]
I'll try it again and provide the warnings it gives, hopefully that gives enough info to fix it. If not, I can look into it.

**Comment by msivasubramaniaan** [comment]
> This error notification I get. It seems identical to the one you described fixing.
> 
> ```
> Get command failed: error: unable to match a printer suitable for the output format "undefined", allowed formats are: custom-columns,custom-columns-file,go-template,go-template-file,json,jsonpath,jsonpath-as-json,jsonpath-file,name,template,templatefile,wide,yaml
> ```
> 
> I also get this error notification, which I expect is related:
> 
> ```
> Error loading document: CodeExpectedError: cannot open k8smsx://loadkubernetescore/deployment-my-pet-alpine?ns%3Ddefault%26value%3Ddeployment%2Fmy-pet-alpine%26_%3D1709053141730. Detail: Get command failed: error: unable to match a printer suitable for the output format "undefined", allowed formats are: custom-columns,custom-columns-file,go-template,go-template-file,json,jsonpath,jsonpath-as-json,jsonpath-file,name,template,templatefile,wide,yaml
> ```

set `vs-kubernetes.outputFormat` as `yaml` default. @datho7561 please try it now

**Review by datho7561 — APPROVED** [review]
This fixes the issue for me! Thanks, Muthu!

**Pull request merged**
