### PR TITLE
Add "OK" and "Cancel" buttons to cluster login quick picks input fields

### PR DESCRIPTION
**Pull request by vrubezhny**
This PR adds a possibility to finish or cancel an entering value operation (like, for new cluster URL, new username, password, token inputs) with pressing an `Enter` or `Cancel` clickable buttons:

image

### CODE REVIEW

**Comment by datho7561** [comment]
If  I try to add a new user, it errors and I get "Excpected a string but got an undefined"

**Comment by vrubezhny** [comment]
No need to use keyboard if you already have your credentials saved:

[Login to a cluster](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/089b7caf-3c62-4e24-831b-e35b373d6655)

You can go back from any step of login workflow:

[Go back from any step](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/d8a09822-61d8-4cc5-b621-06ef277f7c19)

**Comment by vrubezhny** [comment]
> If I try to add a new user, it errors and I get "Excpected a string but got an undefined"

@datho7561 Fixed this as well as few other issues I found (returning back from login method selection)

**Review by datho7561 — APPROVED** [review]
Seems to be working well. Thank you, Victor!

**Pull request merged**
