### PR TITLE
Enable eslint for `.tsx` and webview code

### LINKED ISSUE #3070: Run eslint on `.tsx` files
`eslint` works on `.tsx` files. We should configure `eslint` so that it runs on our `.tsx` files.

### PR DESCRIPTION
**Pull request by datho7561**
Closes #3070

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by mohitsuman** [comment]
@datho7561 can you please rebase this to resolve the conflicts ?

**Comment by datho7561** [comment]
rebased

**Comment by datho7561** [comment]
rebased

**Comment by mohitsuman** [comment]
@datho7561 it seems we would need one more round of rebase :P

**Review by vrubezhny — APPROVED** [review]
Looks good to me, can be rebased with no problems, tests pass OK

**Comment by datho7561** [comment]
Thanks for the review, Victor!

**Pull request merged**
