### PR TITLE
Add, delete and update support on helm repo

### PR DESCRIPTION
**Pull request by msivasubramaniaan**
Fixes: https://github.com/redhat-developer/vscode-openshift-tools/issues/3609

### CODE REVIEW

**Review by datho7561 — CHANGES_REQUESTED** [review]
A few things I noticed:
- Please add integration tests for the helm commands that you're running
- It would be nice if the list of charts in the chart view updated when you add/remove a repo, similar to what we do for Devfile registries
- IMO it's confusing having the list of repos in the tree view and the webview. I think it would be better if we only showed them in the webview, since from the webview you can add, edit and delete repositories, but from the tree view you can't do these things. As an alternative, maybe we can provide add, rename, and delete context menu options and just use quickpicks to set the information, similar to what we did for the devfile registry tree view.

Other things I noticed:
- I ran into this bug, which makes working with helm repos really annoying, I think we should address it in a separate issue though: https://github.com/redhat-developer/vscode-openshift-tools/issues/3622

**Comment by msivasubramaniaan** [comment]
@datho7561 The integration test I'll create the separate PR and fixed all other mentioned points. Please have a look

**Review by datho7561 — APPROVED** [review]
Looks good, and seems to be working reliably. Thanks, Muthu!

**Comment by datho7561** [comment]
Looks like there are merge conflicts

**Comment by datho7561** [comment]
Looks like there are merge conflicts

**Pull request merged**
