### PR TITLE
Increase timeouts for "Import from Git" UI test

### PR DESCRIPTION
**Pull request by datho7561**
Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
How the heck could I possibly be increasing code coverage? That makes no sense.

**Comment by datho7561** [comment]
I double checked, and the coverage is not actually increasing (if I get the coverage from running `main` locally, I get the same numbers as for this PR)

**Comment by datho7561** [comment]
@rgrunber if you have time, could you please take a look at this PR?

**Review by rgrunber — APPROVED** [review]
Tested locally on cli and with the launch config in VS Code. Both seem to be passing.

**Pull request merged**
