### PR TITLE
configure github actions

### LINKED ISSUE #1667: Moving the CI to github actions
Currently the codecov is not working correctly on Azure CI and works on Travis Linux build. To keep only one CI system, its good to move to github actions.

### PR DESCRIPTION
**Pull request by mohitsuman**
Signed-off-by: Mohit Suman <mohit.skn@gmail.com>

Fix #1667

### CODE REVIEW

**Comment by mohitsuman** [comment]
@dgolovin can you please review this. If looks fine, we can merge it and have one CI workflow.

**Comment by mohitsuman** [comment]
> LGTM
> @mohitsuman Did you see that GitHub Action runs for this PR?

No, it has not run for this PR. Do I need to add something more ? @evidolob

**Comment by evidolob** [comment]
No, look there https://github.com/redhat-developer/vscode-openshift-tools/actions did you see any runs or error logs there?
I cannot, it seems that I do not have access to this repository.

**Comment by mohitsuman** [comment]
I also don't see any runs here. It shows the default action page.

**Comment by mohitsuman** [comment]
I did try this on personal openshift-tools repo and test the workflow. https://github.com/mohitsuman/vscode-openshift-tools/pull/5. We can merge this on master and the workflow should be there for openshift-tools.

**Pull request merged**
