### PR TITLE
Don't prompt before switching over to service account on Sandbox

### PR DESCRIPTION
**Pull request by datho7561**
Per our discussion, this makes the experience smoother

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Review by vrubezhny — COMMENTED** [review]
It happens that if I'm logged out and trying to login to sandbox using a provided token, I get the following error:
Screenshot from 2024-02-16 12-02-48

in line 914 of `installPipelineUserContext()`:
```
        const pipelineToken = Buffer.from(pipelineTokenSecret.data.token, 'base64').toString();
```
... because `pipelineTokenSecret` is undefined. (I've taken a look on gathered secrets - there is really no a secret which `matadata.name` is starting with `pipeline-token`).  

As result  I'm logged in, but still using the provided token, not the service account one

**Comment by vrubezhny** [comment]
> (I've taken a look on gathered secrets - there is really no a secret which `matadata.name` is starting with `pipeline-token`).

It doesn't matter if I user this PR or `main` branch, currently the situation is quite the when I try to login to `api-sandbox-m3-1530-p1-openshiftapps-com:6443` (created just today after my previous Developer Sandbox for Red Hat OpenShift account was expired).

So in any case we have to check if the service account token is really available on a cluster

**Comment by datho7561** [comment]
Which ServiceAccounts are available for you on the cluster? You should be able to find this in the OpenShift Console web site switching to "Administrator", then clicking on "User Management" > "ServiceAccounts" in the sidebar.

**Comment by vrubezhny** [comment]
> Which ServiceAccounts are available for you on the cluster? You should be able to find this in the OpenShift Console web site switching to "Administrator", then clicking on "User Management" > "ServiceAccounts" in the sidebar.

image

**Comment by datho7561** [comment]
hmm, so they removed the `pipeline` account, which was the one with the `edit` permissions. I'm now starting to wonder if this is intentionally fixing a security vulnerability. The 15 minute long token is a security mechanism that prevents someone from using a computer where someone forgot to log out to make changes to the cluster. Switching to the long-lived token breaks this mechanism, so I was surprised the cluster provided such an account by default.

**Comment by vrubezhny** [comment]
Yes, looks reasonable.  
But still I believe there should be a way for developers to setup an isolated non-production cluster and get an  account with no any time limitation (for development purposes, and not for production). The other question is if the same cluster is used for the development and for the production - then it's probably not possible.

**Comment by datho7561** [comment]
@vrubezhny I'm going to modify this PR so that it doesn't install the token if there is no `pipeline` ServiceAccount. We should get this in for the release.

**Comment by vrubezhny** [comment]
> @vrubezhny I'm going to modify this PR so that it doesn't install the token if there is no `pipeline` ServiceAccount. We should get this in for the release.

Any news on possibility to have Service Account available in future?

**Review by vrubezhny — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
