### PR TITLE
Wild West Demo App Walkthrough

### LINKED ISSUE #1531: Create Quick start document describing how to deploy wildwest application with extension
Documenting how to deploy wildwest app would be a good candidate for Quick start document. 
App consists of [frontend ](https://github.com/openshift-evangelists/Wild-West-Frontend) and [backend](https://github.com/openshift-evangelists/Wild-West-Backend) and require additional oc commands executed.
Final working app looks like this

image

### PR DESCRIPTION
**Pull request by datho7561**
Closes #1531

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by mohitsuman** [comment]
@datho7561 can you please add a working demo for this ?

**Comment by datho7561** [comment]
> can you please add a working demo for this ?

What do you mean by this? Like a `.gif` of the game working?

**Comment by mohitsuman** [comment]
> > can you please add a working demo for this ?
> 
> What do you mean by this? Like a `.gif` of the game working?

Yes a gif or a demo link of how it works.

**Comment by datho7561** [comment]
@mohitsuman I added the screencast of me playing the game at the end of the walkthrough

**Review by mohitsuman — APPROVED** [review]
LGTM

**Pull request merged**
