### PR TITLE
Components tree view not get refreshed #3318

### PR DESCRIPTION
**Pull request by vrubezhny**
Fixes: #3318

### CODE REVIEW

**Review by datho7561 — CHANGES_REQUESTED** [review]
This doesn't seem to work for me. I put a breakpoint on the added line, and it's never hit when I delete or move the Devfile.

**Comment by vrubezhny** [comment]
Hm...
screencast-component-view-refresh-on-devfile-delete

**Comment by vrubezhny** [comment]
@datho7561 I've updated the PR, could you please  give it another try?

**Comment by datho7561** [comment]
I think that what I was actually running into was that any newly added folders don't get the listener installed. I'll do a bit more testing.

**Comment by datho7561** [comment]
I can't replicate what happened before.

**Review by datho7561 — APPROVED** [review]
Works for me. Thanks, Victor!

**Comment by vrubezhny** [comment]
> I think that what I was actually running into was that any newly added folders don't get the listener installed. I'll do a bit more testing.

This purely can be a reason for not working - but this is another issue - with this PR the removal of a component  `devfile.yaml` was fixed.

Reacting on a  new component folder is added (and a `devfile.yaml` placed into that folder) - is a different story.

**Pull request merged**
