### PR TITLE
add webpack support

### LINKED ISSUE #806: Cofigure webpack build development

### PR DESCRIPTION
**Pull request by mohitsuman**
FIX #806

### CODE REVIEW

**Comment by jrichter1** [comment]
There is a whole bunch of failed tests, but the process still returns 0.

**Comment by jrichter1** [comment]
Plus what @dgolovin  said, sort of defeats the purpose of using webpack.

**Comment by mohitsuman** [comment]
I had configured webpack as per the official docs and how other projects use it. But still tests are failing and return type is 0. Need to check why is this happening. 

Ideally webpack bundle should reduce the size of the build. :(

**Comment by dgolovin** [comment]
This is happening, because you changed compilation script to use webpack and that in turn changed location where compiled files land, to 'dist' folder. Tests are using compilation to build everything before running the tests and then try to run it from `./out/src` folder.

**Comment by mohitsuman** [comment]
@dgolovin You mean that the compilation folder should be changed to `out` ?

**Pull request closed without merging**
