### PR TITLE
[build] Fix vulnerability in @octokit/rest 16.0.0 - 16.43.2

### PR DESCRIPTION
**Pull request by vrubezhny**
```

lodash.set  *
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
fix available via `npm audit fix --force`
Will install @octokit/rest@21.0.2, which is a breaking change
node_modules/lodash.set
  @octokit/rest  16.0.0 - 16.43.2
  Depends on vulnerable versions of lodash.set
  node_modules/@octokit/rest
```

### CODE REVIEW

**Comment by vrubezhny** [comment]
@msivasubramaniaan Do we really  need this code? It seems to be not used anywhere... Or do you plan to use it somehow later?

**Comment by datho7561** [comment]
I was able to completely remove these files without causing any build failures:
- `src/util/getGitService.ts`
- `src/util/githubService.ts`

**Review by msivasubramaniaan — CHANGES_REQUESTED** [review]
`githubServices.ts` and `getGitService.ts` files are no longer needed. We can remove the files from repo and its dependency

**Comment by vrubezhny** [comment]
Closing as not needed anymore

**Pull request closed without merging**
