### PR TITLE
CRC setup is reseted after closing its window #4411

### PR DESCRIPTION
**Pull request by vrubezhny**
Fixes: #4411

### CODE REVIEW

**Comment by vrubezhny** [comment]
@lgrossma Could you please verify if this PR solves #4437 problem of having `settings.json` created like this:

```
{ 
  ...
  "openshiftToolkit.crcBinaryLocation": "~/projects/vscode-openshift-tools/crc/crc-linux-amd64/crc-linux-2.41.0-amd64/crc",   
  "openshiftToolkit": {
    ...
    "crcBinaryLocation": null,
    ...
  },
  ...
} 
```

**Comment by vrubezhny** [comment]
Also, I've changed the 'crcNameServer` setting to `vscode.ConfigurationTarget.Global` to align it to the rest of the CRC settings... I don't see any reason for it to be saved as a Workspace setting rather than a Global one. 
Please open an issue if this setting is still to be saved as  a Workspace setting

**Review by datho7561 — COMMENTED** [review]
From my testing, this works, and the code changes look good. I would be interested to see if it solves Lukas' problem

**Review by lgrossma — APPROVED** [review]
Works great now! thx

**Pull request merged**
