### PR TITLE
[WIP] initial implementation for UHC explorer

### PR DESCRIPTION
**Pull request by gorkem**
This is work in progress and still requires.
- [ ] A proper way to update current kubernetes context with the information retrieved from UHC 
- [ ] Error handling for errors received from backend service
- [ ] Refresh button

### CODE REVIEW

**Comment by dgolovin** [comment]
testPR

**Comment by bmicklea** [comment]
Are there more details on what the UHC explorer is?

**Comment by gorkem** [comment]
@bmicklea UHC Explorer is just the name I have used to define the vscode explorer section that shows the list of clusters defined on the UHC.

**Comment by gorkem** [comment]
Closing this PR as it is not relevant anymore

**Pull request closed without merging**
