### PR TITLE
In devfile search view, add an option to filter by debug support and …

### PR DESCRIPTION
**Pull request by vrubezhny**
…deploy support #3086

Fixes: #3086

### CODE REVIEW

**Comment by datho7561** [comment]
If I do "+" in the "Components" section of the OpenShift view, then select "From template project", the search results are empty.

**Comment by vrubezhny** [comment]
> If I do "+" in the "Components" section of the OpenShift view, then select "From template project", the search results are empty.

@datho7561  I've fixed "Components-> "+" -> From template project` view.

Also, I removed the `Filter by tags` and left only `Filter by capabilities`  section  (as the tags are not really requested in the this issue) .

Screenshot from 2023-09-18 18-32-14

**Comment by vrubezhny** [comment]
> Okay, a few more comments:  (https://github.com/redhat-developer/vscode-openshift-tools/pull/3280#issuecomment-1724074005)

I believe these issues are fixed now.

**Comment by vrubezhny** [comment]
Changed to clickable labels instead of checkboxes, but still have problems with column and element  positioning:

Screenshot from 2023-09-19 14-55-22

**Comment by vrubezhny** [comment]
This is how the latest view version looks like:
image

**Review by datho7561 — DISMISSED** [review]
Looks good and works well. Thanks, Victor!

**Comment by vrubezhny** [comment]
This is how the capability and tag filters look like for the `Devfile Registry` and `Select Template Project from Devfile` views:

image

**Review by datho7561 — DISMISSED** [review]
Once the merge conflicts are addressed, this PR is good to me merged

**Pull request merged**
