### PR TITLE
Dispose of watchers in serverless function code

### PR DESCRIPTION
**Pull request by datho7561**
One part of #3120

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
Test failures seem legitimate and indicate that a modal has popped up, preventing interaction with VS Code. This usually means that VS Code is alerting the user that an extension has failed badly. I'll have to investigate.

**Comment by vrubezhny** [comment]
This change looks good to me... but it's not enough...

When I have running the development vscode instance, plus started debugging the extension, hen started Dev for a component in OS  View then...
... in Systen Terminal (outside of any vscode nstance) command line I run `npm test`, I heve the following test failed:

```
  File Watch Utility
      ✔ watchFileForContextChange ensures the location exists: 0ms
      ✔ watchFileForContextChange creates a file watcher for the given path: 1ms
      ✔ watchFileForContextChange returns a content change notifier: 0ms
      1) emits change message when context changes
  Suite duration: 0.014 s, Tests: 4
...
  1 failing
  1) File Watch Utility
       emits change message when context changes:
     Error: EMFILE: too many open files, watch '/tmp'
      at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
      at Object.watch (node:fs:2322:34)
      at Function.watchFileForContextChange (src/util/watch.ts:18:46)
      at /home/jeremy/projects/vscode-openshift-tools/source/vscode-openshift-tools/test/unit/util/watch.test.ts:57:36
      at Generator.next (<anonymous>)
      at /home/jeremy/projects/vscode-openshift-tools/source/vscode-openshift-tools/out/test/unit/util/watch.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (out/test/unit/util/watch.test.js:8:12)
      at Context.<anonymous> (test/unit/util/watch.test.ts:52:66)
      at processImmediate (node:internal/timers:466:21)

Test failures: 1
Exit code:   1
Failed to run tests
```

Which brings me to [WatchUtil.watchFileForContextChange(...)](https://github.com/redhat-developer/vscode-openshift-tools/blob/960762255150232a818d3fd0a0aa2fa80ab79b7d/src/util/watch.ts#L18C20-L18C20) creating a File Watcher and at least two client views which invoke this method  (and close the  File Watchers) plus the test itself which  never close the produced File Watchers. 
I don't believe that two File Watchers opened by the utility method  client views can male the file watcher counter to overload, but the test cases for sure should also close the created File Watchers as this can force the subsequent tests or some functions of the running extension to fail.

**Review by vrubezhny — DISMISSED** [review]
Looks good to me

**Comment by datho7561** [comment]
I'll address the comment about the test in this PR as well; might as well.

**Pull request merged**
