### PR TITLE
Integration test suite for `odo` commands we call

### LINKED ISSUE #2799: Integration tests to verify cli tool commands used in extension works with new version released
To avoid compatibility issues between odo releases there should be integration tests to run:
* with latest nightly oc/odo build to detect problems early
* with latest official oc/odo release to verify compatibility before extension release

### PR DESCRIPTION
**Pull request by datho7561**
- remove unused commands from `commands.ts` and unused methods from `odo.ts`
  - Notably, remove `ODO.getApplications()`, `ODO.getComponents()`, and the in-memory tree representing the cluster state, since they don't work properly and we have replacements for them
- rewrite integration tests for `commands.ts` and `odo.ts`
- report test coverage for integration tests
- add the integration tests to the UI test Jenkinsfile workflow

Depends on #2865, #2863, #2862

Fixes #2799

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
to run these tests locally
- start `crc` locally
- figure out the URL of the cluster api
- run `npm run test-integration:coverage` with the environment variable `CLUSTER_URL` set to the cluster api url

**Comment by datho7561** [comment]
Currently, I'm not saving the coverage report for the integration tests anywhere, since I can't run the tests through GitHub Actions and aggregate the results with the coverage for the unit tests.

Come to think of it, it might be better to avoid running it as a part of the CI workflow. I'll make that change quickly.

**Comment by datho7561** [comment]
@rgrunber @msivasubramaniaan @mohitsuman alright, this PR is ready for review

**Review by rgrunber — APPROVED** [review]
I'm fine with merging this. Tests seem to all pass when run locally with a CRC test instance.

**Pull request merged**
