### PR TITLE
Fix linter errors caused by vscode-extension-tester 5.9.1

### PR DESCRIPTION
**Pull request by datho7561**

### CODE REVIEW

**Comment by datho7561** [comment]
@vrubezhny We need to merge this to address the linting errors so that the tests can run properly.

**Comment by datho7561** [comment]
The tests are failing consistently, perhaps due to a timeout issue

**Comment by datho7561** [comment]
UI tests failed; I think vscode-extension-tester doesn't work with node 18

**Comment by datho7561** [comment]
I'm going to try downgrading to 5.6.0, which works with Node 18

**Comment by datho7561** [comment]
@vrubezhny seems like the UI tests are running again. We either need to downgrade the testing framework to 5.6.0 (which I have currently with this PR) or switch to running the tests with Node 16.

**Review by vrubezhny — APPROVED** [review]
I'm OK to merge this PR in. And I tried doing the same fixup for the other DB update PRs (probably after I tried uvscode-extension-tester update, so new tester (5.9.1)  was actually used in my case)

**Pull request merged**
