### PR TITLE
UI implementation for helm UI

### PR DESCRIPTION
**Pull request by msivasubramaniaan**
Signed-off-by: msivasubramaniaan <msivasub@redhat.com>

### CODE REVIEW

**Comment by msivasubramaniaan** [comment]
@dgolovin Can you please review this PR?

**Comment by dgolovin** [comment]
@msivasubramaniaan please add reference to the issue.

**Review by rgrunber — APPROVED** [review]
Tried this out and works well for me. Yes, I would link to the issue either in the top comment (eg. - Fixes # ...) or under the Development tab (below Milestone).  I noticed I needed to use `export NODE_OPTIONS=--max_old_space_size=8192` to compile this change. Otherwise I'd see 

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
```

If that's expected, then feel free to merge. Just make sure to squash these into a single commit.

**Comment by msivasubramaniaan** [comment]
> Tried this out and works well for me. Yes, I would link to the issue either in the top comment (eg. - Fixes # ...) or under the Development tab (below Milestone). I noticed I needed to use `export NODE_OPTIONS=--max_old_space_size=8192` to compile this change. Otherwise I'd see
> 
> ```
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
> ```
> 
> If that's expected, then feel free to merge. Just make sure to squash these into a single commit.

@rgrunber May I know where you have made a node_options change? we already have [PR](https://github.com/redhat-developer/vscode-openshift-tools/pull/2767) for that and it was merged long back

**Comment by rgrunber** [comment]
In order to build the extension locally (`npm run compile`), I needed to do it on my own machine.

**Pull request merged**
