### PR TITLE
[test] Add integration test suite and test for running a component co…

### PR DESCRIPTION
**Pull request by vrubezhny**
…mmand

Issue: #2811

### CODE REVIEW

**Comment by datho7561** [comment]
I get `AssertionError [ERR_ASSERTION]: Start Dev failed: I0825 11:12:19.168688   77369 starterserver.go:123] API Server started at localhost:20000/api/v1` for the test. I guess odo using stderr for some logging, which is causing the test to detect odo dev failing, which is causing the test to fail.

**Comment by vrubezhny** [comment]
> I get `AssertionError [ERR_ASSERTION]: Start Dev failed: I0825 11:12:19.168688 77369 starterserver.go:123] API Server started at localhost:20000/api/v1` for the test. I guess odo using stderr for some logging, which is causing the test to detect odo dev failing, which is causing the test to fail.

This most likely means that "Start Dev" hasn't finished in 60 seconds.
When starting Dev it sends some messages like `I0825 11:12:19.168688 77369 starterserver.go:123] API Server started at localhost:20000/api/v1` to the error stream for some reason - while this is not an error at all imho, but it's reported to the error stream.
But starting  Dev takes some time and when 60 seconds timeout is reached I do report the received errors as `fail(...)` message.
So actually the reason was a timeout happened.

**Comment by datho7561** [comment]
I'm running the suite a few times to see how stable it is, and it looks like it was just a one-off failure

**Review by datho7561 — APPROVED** [review]
Looks good to me. Thanks, Victor!

**Pull request merged**
