### PR TITLE
Supports multiple Helm repos

### PR DESCRIPTION
**Pull request by msivasubramaniaan**
Fixes: https://github.com/redhat-developer/vscode-openshift-tools/issues/3113
helm-multi-repo

### CODE REVIEW

**Comment by msivasubramaniaan** [comment]
Currently `CUD` operations were missing on helm on our extension. Please provide your vote for adding those based on it we can create a ticket on our backlog

**Review by vrubezhny — DISMISSED** [review]
Looks good to me.

Filtering works very similar to what we have in Devfile Registry.

**Comment by datho7561** [comment]
I've changed my mind on having filters for keywords, I think we should remove them. There are far too many unique keywords to display them nicely in the UI:

Screenshot from 2023-11-15 10-04-10

(for reference here are my installed helm repos:)

```
❯ helm repo list
NAME            URL                                                
bitnami-repo    https://charts.bitnami.com/bitnami                 
openshift       https://charts.openshift.io/                       
istio           https://istio-release.storage.googleapis.com/charts
ot-helm         https://ot-container-kit.github.io/helm-charts/    
wildfly         https://docs.wildfly.org/wildfly-charts/           
mongodb         https://mongodb.github.io/helm-charts
```

**Comment by vrubezhny** [comment]
> I've changed my mind on having filters for keywords, I think we should remove them. There are far too many unique keywords to display them nicely in the UI:

Yeah. This looks too big. Agreed.

**Comment by msivasubramaniaan** [comment]
Is it okay to show only first two keywords on each chart if it has more than two keywords. In that way atleast we can reduce the size. Wdyt?

**Comment by vrubezhny** [comment]
I'm mot sure if showing the only a few  first keywords will be useful here since we don't know the importance of each keyword...

Probably we can try calculating the keyword i"mportance" based on the position of keyword among the other keywirds in the same helm chart and the number of occurrence of each keyword and then we list the first N most "important" keywords...
 
But still, making such assumptions looks very artificial, given the variety in keywords shown on David's screenshot,  so I don't know if such a selection will be useful...

@datho7561 WDYT?

**Comment by datho7561** [comment]
I agree with Victor.

I think sorting the keywords by occurrence, and then only allow filtering by the top 30 (or some other number) could be helpful. However, the implementation for this will get complex:
- Performing the calculation could get expensive, given there are so many tags
- As a result, we need to be careful to cache the results of the calculation so that it only redoes it when the charts change (i.e. a repo is added or deleted)

**Review by vrubezhny — DISMISSED** [review]
Looks good.

Agree on that we can create a separate issue for adding keywords filtering if needed

**Review by datho7561 — CHANGES_REQUESTED** [review]
A few things I noticed:

1. I tried installing a few charts from the MongoDB helm repo (https://mongodb.github.io/helm-charts/) onto a KinD cluster, but I get the following error message in the webview: 
```
chart "enterprise-database" matching 1.13.0 not found in openshift index. (try 'helm repo update'): no chart name found `my-db`
```
I'm not doing anything related to openshift, so why does the error message mention openshift? **update:** I can replicate the same issue when using `crc`, it's not specific to `kind`.

2. The checkbox for hiding entries from the OpenShift Helm repo is disabled. I think it would be nice to enable it. My use case for hiding the OpenShift Helm charts is that I can't install these charts on a non-OpenShift cluster, since the charts use DeploymentConfigs (which are specific to OpenShift clusters).

3. It would be nice to remove the horizontal line below the list of "provider types" checkboxes so that it's similar to the Devfile registry

The last two comments aren't that important, but I think we should fix the first one before merging this PR.

**Comment by msivasubramaniaan** [comment]
> A few things I noticed:
> 
> 1. I tried installing a few charts from the MongoDB helm repo (https://mongodb.github.io/helm-charts/) onto a KinD cluster, but I get the following error message in the webview:
> 
> ```
> chart "enterprise-database" matching 1.13.0 not found in openshift index. (try 'helm repo update'): no chart name found `my-db`
> ```
> 
> I'm not doing anything related to openshift, so why does the error message mention openshift? **update:** I can replicate the same issue when using `crc`, it's not specific to `kind`.
> 
> 2. The checkbox for hiding entries from the OpenShift Helm repo is disabled. I think it would be nice to enable it. My use case for hiding the OpenShift Helm charts is that I can't install these charts on a non-OpenShift cluster, since the charts use DeploymentConfigs (which are specific to OpenShift clusters).
> 3. It would be nice to remove the horizontal line below the list of "provider types" checkboxes so that it's similar to the Devfile registry
> 
> The last two comments aren't that important, but I think we should fix the first one before merging this PR.

Thanks for the good catch @datho7561. The reason was the repo name was hardcoded with 'openshift'. Now I have changed and made it dynamically. Please review the latest code

**Review by datho7561 — APPROVED** [review]
Looks good and works well. Great work, Muthu!

**Pull request merged**
